version: '3'
services:
  casper_db:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=secret21
     - MYSQL_DATABASE=casper_db
    volumes:
     - casper_db_data:/var/lib/mysql
    restart: always
  casper:
    image: dannyx21/casper:1.34
    ports:
    - 7000:8000
    environment:
     - DATABASE_HOST=casper_db
     - DATABASE_PORT=3306
     - DATABASE_PASS=secret21
     - DATABASE_NAME=casper_db
    volumes:
     - casper_data:/casper/
    restart: always
    depends_on:
     - casper_db
  casper_app:
    image: dannyx21/casper_app:1.5
    ports:
    - 80:8080
    environment:
     - VUE_APP_API_URI=https://backend.dannyx.net/
    depends_on:
     - casper_db
     - casper
    restart: always
volumes:
 casper_db_data:
 casper_data: